storage: ../tmp/local-registry/storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
  zod2md:
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    proxy: npmjs

log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true

security:
  api:
    migrateToSecureLegacySignature: true
